POST http://localhost:3000/signup
Content-Type: application/json

{
  "name": "Людмила1",
  "about": "Студентка",
  "avatar": "http://cdn23.us1.fansshare.com/photos/alicegreczyn/alice-greczyn-conde-nast-traveler-hot-list-llfnqjehgx-beach-1267417174.jpg",
  "email": "hello123@gmail.com",
  "password": "Hello12345"
}